name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
      - feature/*
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push backend Docker image
        run: |
          docker build -t netflix-clone-backend ./backend
          docker tag netflix-clone-backend:latest YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/netflix-clone:latest
          docker push YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/netflix-clone:latest

      - name: Run backend tests
        run: |
          docker run --rm netflix-clone-backend:latest python -m unittest discover -s backend/tests

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./infrastructure/ecs-task-definition.json
          service: netflix-clone-service
          cluster: netflix-clone-cluster
          wait-for-service-stability: true
