name: Destroy Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
      - destroy

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: infrastructure/terraform
